import os
import dis
import marshal
from rich.panel import Panel
from rich.align import Align
from rich import box
from rich.prompt import Prompt
from rich.console import Console
from rich.syntax import Syntax
import io

class PythonDisassembler:
    def __init__(self, console: Console):
        self.console = console
        self.col_neon = "#00ffcc"
        self.col_dim = "bright_black"

    def _disassemble_pyc(self, file_path: str) -> str:
        with open(file_path, "rb") as f:
            # Skip the magic number and timestamp
            f.read(16)
            code_obj = marshal.load(f)
            
            # Capture dis output
            output = io.StringIO()
            dis.dis(code_obj, file=output)
            return output.getvalue()

    def run(self):
        c = self.console
        c.print()
        c.print(Align.center(Panel(
            f"[bold {self.col_neon}]✦ PYTHON BYTECODE DISASSEMBLER ✦[/bold {self.col_neon}]\n\n"
            f"[{self.col_dim}]Decompile/Disassemble Python .pyc files into native Bytecode Instructions.\n"
            f"Results are automatically exported to the 'exports' folder.[/{self.col_dim}]",
            border_style=self.col_neon,
            box=box.ROUNDED,
            padding=(1, 4)
        )))
        c.print()

        export_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "exports")
        os.makedirs(export_dir, exist_ok=True)

        while True:
            file_path = Prompt.ask(f"  [{self.col_neon}]Path to compiled .pyc (or 'q' to quit)[/{self.col_neon}]").strip()
            
            if file_path.lower() == 'q':
                break
                
            if not file_path:
                continue
                
            # Clean up paths (Windows drag and drop often adds quotes or spaces)
            file_path = file_path.strip('"').strip("'").strip()
            
            if not os.path.isfile(file_path) or not file_path.lower().endswith('.pyc'):
                c.print("  [bold red]✗ File not found or not a .pyc file.[/bold red]\n")
                continue
                
            c.print(f"\n  [dim]Disassembling {os.path.basename(file_path)}...[/dim]")
            try:
                output = self._disassemble_pyc(file_path)
                
                if output:
                    # Write to export file
                    out_name = os.path.basename(file_path).replace('.pyc', '_decompiled.py.asm')
                    out_path = os.path.join(export_dir, out_name)
                    
                    with open(out_path, "w", encoding="utf-8") as f:
                        f.write(f"# Disassembled Bytecode for {os.path.basename(file_path)}\n")
                        f.write(f"# Generated by Cosmos.win Python Disassembler\n")
                        f.write("-" * 60 + "\n\n")
                        f.write(output)

                    with c.pager(styles=True):
                        c.print(f"[bold bright_cyan]Decompiled Bytecode for {os.path.basename(file_path)}[/bold bright_cyan]")
                        c.print("-" * 50)
                        syntax = Syntax(output, "python", theme="monokai", line_numbers=True)
                        c.print(syntax)
                        
                c.print(f"  [bold green]✓ Disassembly finished. Exported to:[/bold green] {out_path}")
                try:
                    # Open explorer to the export file
                    if os.name == 'nt':
                        os.startfile(export_dir)
                except Exception:
                    pass
                c.print()
                
            except Exception as e:
                c.print(f"  [bold red]✗ Unexpected error decompiling .pyc (Wrong python version?): {e}[/bold red]\n")
                
        c.input(f"\n  [{self.col_dim}]Press Enter to return...[/{self.col_dim}]")
